#!/usr/bin/env python3
"""
Script to fix test files by adding missing features to the Required Features comment.
Parses error output and updates the corresponding Java files.
"""

import os
import re
import sys

# Parse error messages to extract file -> detected features mapping
errors = """
Tiny_ForkJoin_Java7.java: CONCURRENT_API, FORK_JOIN
Combo_VarargsGenericsAutoboxing_Java5.java: VARARGS, GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Combo_LambdaStreamMethodRef.java: AUTOBOXING, METHOD_REFERENCES, LAMBDAS, STREAM_API
Tiny_Optional_Java8.java: OPTIONAL, GENERICS
Edge_VarAllContexts_Java10.java: FOR_EACH, GENERICS, IO_API, VAR, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK
Tiny_YieldSimple_Java14.java: YIELD, SWITCH_EXPRESSIONS
Tiny_Diamond_Java7.java: GENERICS, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Java14_SwitchExpressions.java: SWITCH_EXPRESSIONS, SWITCH_MULTIPLE_LABELS
Tiny_AutoboxLooksModern_Java5.java: GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Tiny_WatchService_Java7.java: WATCH_SERVICE, NIO2
Combo_PrivateDefaultInterface_Java9.java: INNER_CLASSES, PRIVATE_INTERFACE_METHODS, DEFAULT_INTERFACE_METHODS
Tiny_VThread_Java21.java: LAMBDAS, VIRTUAL_THREADS
Tiny_TryWithResources_Java7.java: IO_API, TRY_WITH_RESOURCES
Edge_LambdaAllVariations.java: GENERICS, LAMBDAS
Edge_MultipleUnderscores.java: UNDERSCORES_IN_LITERALS, BINARY_LITERALS
Tiny_TryEffectivelyFinal_Java9.java: IO_API, TRY_WITH_RESOURCES, TRY_WITH_EFFECTIVELY_FINAL
Tiny_Generics_Java5.java: GENERICS, COLLECTIONS_FRAMEWORK
Java16_LocalEnums.java: ENUMS, LOCAL_ENUMS, SWITCH_EXPRESSIONS
Tiny_Reactive_Java9.java: GENERICS, CONCURRENT_API, REACTIVE_STREAMS
Combo_GenericsDiamondForEach.java: FOR_EACH, GENERICS, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Tiny_MultiCatch_Java7.java: IO_API, MULTI_CATCH, JDBC
Java9_TryWithEffectivelyFinal.java: IO_API, TRY_WITH_RESOURCES, TRY_WITH_EFFECTIVELY_FINAL
Tiny_SealedInner_Java17.java: INNER_CLASSES, SEALED_CLASSES
Tiny_RecordPattern_Java21.java: RECORDS, PATTERN_MATCHING_INSTANCEOF, RECORD_PATTERNS
Tiny_LocalEnum_Java16.java: ENUMS, LOCAL_ENUMS
Edge_NestedRecordPatternsGuards_Java21.java: RECORDS, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING
Java11_FlightRecorder.java: NIO, ANNOTATIONS, FLIGHT_RECORDER, TRY_WITH_RESOURCES, NIO2
Edge_VarInForLoop.java: FOR_EACH, VAR, COLLECTIONS_FRAMEWORK, AUTOBOXING
Tiny_VarTry_Java10.java: IO_API, VAR, TRY_WITH_RESOURCES
Tiny_Serial_Java1.java: IO_API, SERIALIZATION
Tiny_StaticInterface_Java8.java: STATIC_INTERFACE_METHODS, INNER_CLASSES
Tiny_Unnamed_Java22.java: FOR_EACH, UNNAMED_VARIABLES, COLLECTION_FACTORY_METHODS
Combo_VarLambdaRefFactoryStream.java: VAR_IN_LAMBDA, VAR, COLLECTION_FACTORY_METHODS, METHOD_REFERENCES, LAMBDAS, STREAM_API
Combo_SealedRecordsPattern.java: RECORDS, INNER_CLASSES, SWITCH_EXPRESSIONS, SEALED_CLASSES, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING
Tiny_GenericsLooksVar_Java5.java: GENERICS, COLLECTIONS_FRAMEWORK
Tiny_DiamondAnon_Java9.java: INNER_CLASSES, GENERICS, DIAMOND_WITH_ANONYMOUS, DIAMOND_OPERATOR
Java7_TryWithResources.java: IO_API, TRY_WITH_RESOURCES
Tiny_DeserializationFilters_Java17.java: DESERIALIZATION_FILTERS, IO_API
Combo_Java7AllFeatures.java: GENERICS, UNDERSCORES_IN_LITERALS, IO_API, MULTI_CATCH, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK, BINARY_LITERALS, STRINGS_IN_SWITCH, DIAMOND_OPERATOR
Tiny_Sealed_Java17.java: INNER_CLASSES, SEALED_CLASSES
Combo_GenericsVarDiamond_Java10.java: GENERICS, VAR, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Tiny_TryInline_Java7.java: IO_API, TRY_WITH_RESOURCES
Combo_AnnotationsGenericsVarargs.java: FOR_EACH, VARARGS, GENERICS, ANNOTATIONS
Java14_SwitchMultipleLabels.java: SWITCH_EXPRESSIONS, SWITCH_MULTIPLE_LABELS
Tiny_Serialization_Java1.java: IO_API, SERIALIZATION
Combo_AnnotationsEnumsGenericsForEach.java: FOR_EACH, GENERICS, ENUMS, ANNOTATIONS, COLLECTIONS_FRAMEWORK
Combo_VarTryLambda.java: IO_API, VAR, TRY_WITH_RESOURCES, TRY_WITH_EFFECTIVELY_FINAL, LAMBDAS
Tiny_JAXWS_Java6.java: ANNOTATIONS, XML_API, JAX_WS
Java9_PrivateInterfaceMethods.java: STATIC_INTERFACE_METHODS, INNER_CLASSES, PRIVATE_INTERFACE_METHODS, DEFAULT_INTERFACE_METHODS
Tiny_UnixDomainSockets_Java16.java: NIO, UNIX_DOMAIN_SOCKETS
Edge_InterfaceAllMethods.java: STATIC_INTERFACE_METHODS, INNER_CLASSES, PRIVATE_INTERFACE_METHODS, DEFAULT_INTERFACE_METHODS
Combo_RecordSealedPattern_Java21_Advanced.java: RECORDS, INNER_CLASSES, VAR, SEALED_CLASSES, PATTERN_MATCHING_INSTANCEOF, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING
Tiny_SwitchNull_Java21.java: SWITCH_NULL_DEFAULT, STRINGS_IN_SWITCH
Tiny_LocalIface_Java16.java: INNER_CLASSES, LAMBDAS, LOCAL_INTERFACES
Edge_InterfaceAllMethodTypes_Java9.java: STATIC_INTERFACE_METHODS, INNER_CLASSES, PRIVATE_INTERFACE_METHODS, DEFAULT_INTERFACE_METHODS
Java7_ForkJoin.java: INNER_CLASSES, GENERICS, ANNOTATIONS, CONCURRENT_API, FORK_JOIN
Combo_Java8AllFeatures.java: STATIC_INTERFACE_METHODS, OPTIONAL, INNER_CLASSES, GENERICS, DATE_TIME_API, COLLECTIONS_FRAMEWORK, METHOD_REFERENCES, LAMBDAS, DEFAULT_INTERFACE_METHODS, STREAM_API
Tiny_UnnamedFor_Java22.java: FOR_EACH, UNNAMED_VARIABLES
Edge_AllLambdaVariations_Java8.java: GENERICS, LAMBDAS
Combo_LambdaMethodRefStream_Java8.java: GENERICS, COLLECTIONS_FRAMEWORK, METHOD_REFERENCES, LAMBDAS, STREAM_API
Tiny_Varargs_Java5.java: FOR_EACH, VARARGS
Java21_SequencedCollections.java: GENERICS, SEQUENCED_COLLECTIONS, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Java14_Yield.java: YIELD, SWITCH_EXPRESSIONS
Tiny_MethodRefField_Java8.java: GENERICS, METHOD_REFERENCES
Combo_RecordsSealedPatternSwitchText.java: RECORDS, INNER_CLASSES, SWITCH_EXPRESSIONS, TEXT_BLOCKS, SEALED_CLASSES, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING
Tiny_Gatherers_Java24.java: STREAM_GATHERERS, AUTOBOXING, STREAM_API
Tiny_LocalEnumSimple_Java16.java: ENUMS, LOCAL_ENUMS
Edge_SealedNonSealed.java: INNER_CLASSES, SEALED_CLASSES
Java21_SwitchNullDefault.java: SWITCH_EXPRESSIONS, SWITCH_NULL_DEFAULT
Combo_RepeatingTypeAnnotations_Java8.java: REFLECTION, ANNOTATIONS, REPEATING_ANNOTATIONS
Tiny_DefaultMethod_Java8.java: INNER_CLASSES, DEFAULT_INTERFACE_METHODS
Combo_AnonymousDiamondFactory_Java9.java: INNER_CLASSES, GENERICS, COLLECTION_FACTORY_METHODS, COLLECTIONS_FRAMEWORK, DIAMOND_WITH_ANONYMOUS, DIAMOND_OPERATOR
Edge_AutoboxingCollections.java: GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Java25_ScopedValues.java: GENERICS, SCOPED_VALUES, LAMBDAS
Combo_GatherersTeeing_Java24.java: STREAM_GATHERERS, AUTOBOXING, LAMBDAS, STREAM_API, COLLECTORS_TEEING
Edge_StaticNestedGenerics_Java5.java: INNER_CLASSES, GENERICS
Tiny_VirtualThread_Java21.java: LAMBDAS, VIRTUAL_THREADS
Tiny_ScopedValues_Java25.java: GENERICS, SCOPED_VALUES
Tiny_SwingWorker_Java6.java: GENERICS, SWING, SWING_WORKER
Java24_ClassFileAPI.java: FOR_EACH, CLASS_FILE_API, LAMBDAS
Tiny_DeserFilter_Java17.java: DESERIALIZATION_FILTERS, IO_API
Edge_GenericRecord.java: RECORDS, GENERICS, DIAMOND_OPERATOR
Tiny_UnnamedLambda_Java22.java: GENERICS, UNNAMED_VARIABLES, LAMBDAS
Tiny_StreamAPI_Java8.java: AUTOBOXING, LAMBDAS, STREAM_API
Java10_Var.java: FOR_EACH, GENERICS, VAR, COLLECTIONS_FRAMEWORK
Tiny_RepeatAnno_Java8.java: REFLECTION, ANNOTATIONS, REPEATING_ANNOTATIONS
Combo_StreamOptionalRefLambda.java: OPTIONAL, GENERICS, COLLECTIONS_FRAMEWORK, METHOD_REFERENCES, LAMBDAS, STREAM_API
Combo_Java5AllFeatures.java: FOR_EACH, VARARGS, GENERICS, ENUMS, ANNOTATIONS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Java8_TypeAnnotations.java: FOR_EACH, GENERICS, ANNOTATIONS, COLLECTIONS_FRAMEWORK, TYPE_ANNOTATIONS
Tiny_WildcardLooksPattern_Java5.java: FOR_EACH, GENERICS, COLLECTIONS_FRAMEWORK
Tiny_StaticLooksModule_Java5.java: STATIC_IMPORT, AUTOBOXING
Edge_StaticNestedGenerics.java: INNER_CLASSES, GENERICS
Edge_AutoboxingCollections_Java5.java: GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Tiny_WebServer_Java18.java: SIMPLE_WEB_SERVER, NIO, VAR, NIO2
Tiny_TypeAnno_Java8.java: GENERICS, ANNOTATIONS, COLLECTIONS_FRAMEWORK, TYPE_ANNOTATIONS
Tiny_VarLambdaAnno_Java11.java: VAR_IN_LAMBDA, GENERICS, ANNOTATIONS, LAMBDAS
Tiny_Teeing_Java12.java: VAR, COLLECTION_FACTORY_METHODS, AUTOBOXING, LAMBDAS, STREAM_API, COLLECTORS_TEEING
Tiny_PrivateIface_Java9.java: PRIVATE_INTERFACE_METHODS, DEFAULT_INTERFACE_METHODS
Java8_StaticInterfaceMethods.java: STATIC_INTERFACE_METHODS, INNER_CLASSES, AUTOBOXING, DEFAULT_INTERFACE_METHODS
Edge_VirtualThreadsExecutor.java: VAR, TRY_WITH_RESOURCES, CONCURRENT_API, LAMBDAS, VIRTUAL_THREADS
Tiny_LocalIfaceNested_Java16.java: INNER_CLASSES, LOCAL_INTERFACES
Combo_VarTryLambda_Java11_Advanced.java: VAR_IN_LAMBDA, IO_API, VAR, TRY_WITH_RESOURCES, LAMBDAS
Edge_GuardedPattern.java: SWITCH_EXPRESSIONS, SWITCH_PATTERN_MATCHING
Edge_DeeplyNestedGenerics.java: GENERICS, COLLECTIONS_FRAMEWORK
Edge_GenericRecords_Java16.java: RECORDS, GENERICS, DIAMOND_OPERATOR
Tiny_SwitchMultiLabel_Java14.java: SWITCH_EXPRESSIONS, SWITCH_MULTIPLE_LABELS
Tiny_SwitchPattern_Java21.java: SWITCH_EXPRESSIONS, SWITCH_PATTERN_MATCHING
Combo_MultiCatchTryDiamond_Java7.java: GENERICS, IO_API, MULTI_CATCH, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Tiny_JAXB_Java6.java: JAXB, XML_API
Edge_VargsSafeGenerics.java: VARARGS, GENERICS, ANNOTATIONS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Tiny_LocalInterface_Java16.java: INNER_CLASSES, LAMBDAS, LOCAL_INTERFACES
Edge_SequencedGetFirstLast_Java21.java: GENERICS, SEQUENCED_COLLECTIONS, COLLECTION_FACTORY_METHODS
Combo_TryMultiCatchDiamond.java: GENERICS, IO_API, MULTI_CATCH, TRY_WITH_RESOURCES, DIAMOND_OPERATOR
Combo_InterfaceMethodsLambda_Java8.java: STATIC_INTERFACE_METHODS, INNER_CLASSES, LAMBDAS, DEFAULT_INTERFACE_METHODS
Tiny_RecPattern_Java21.java: RECORDS, PATTERN_MATCHING_INSTANCEOF, RECORD_PATTERNS
Edge_RecordImplementsSealed.java: RECORDS, INNER_CLASSES, SEALED_CLASSES
Tiny_PrivateInterface_Java9.java: INNER_CLASSES, PRIVATE_INTERFACE_METHODS, DEFAULT_INTERFACE_METHODS
Tiny_ModuleImport_Java25.java: MODULE_IMPORTS, GENERICS, COLLECTION_FACTORY_METHODS
Java7_BinaryLiterals.java: UNDERSCORES_IN_LITERALS, BINARY_LITERALS
Edge_SequencedGetFirstLast.java: GENERICS, SEQUENCED_COLLECTIONS, COLLECTION_FACTORY_METHODS
Tiny_MethodRef_Java8.java: GENERICS, METHOD_REFERENCES
Tiny_Yield_Java14.java: YIELD, SWITCH_EXPRESSIONS
Tiny_StackWalk_Java9.java: STACK_WALKING, LAMBDAS
Tiny_CopyOf_Java10.java: COLLECTION_COPY_OF, VAR, COLLECTION_FACTORY_METHODS
Java8_MethodReferences.java: GENERICS, COLLECTIONS_FRAMEWORK, METHOD_REFERENCES
Edge_SealedNonSealed_Java17.java: INNER_CLASSES, SEALED_CLASSES
Combo_EnumAnnotationGenerics_Java5.java: GENERICS, ENUMS, ANNOTATIONS, COLLECTIONS_FRAMEWORK
Edge_VarAllContexts.java: FOR_EACH, GENERICS, IO_API, VAR, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK
Tiny_DiamondReturn_Java7.java: GENERICS, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Tiny_ForEachLooksStream_Java5.java: FOR_EACH, GENERICS, COLLECTIONS_FRAMEWORK
Java8_Optional.java: OPTIONAL, GENERICS, AUTOBOXING, METHOD_REFERENCES, LAMBDAS
Tiny_Gatherer_Java24.java: STREAM_GATHERERS, STREAM_API
Edge_AllMethodReferences_Java8.java: GENERICS, METHOD_REFERENCES
Combo_VarDiamondFactory.java: GENERICS, VAR, COLLECTION_FACTORY_METHODS, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Edge_MultipleUnderscores_Java7.java: UNDERSCORES_IN_LITERALS, BINARY_LITERALS
Java22_UnnamedVariables.java: FOR_EACH, RECORDS, GENERICS, UNNAMED_VARIABLES, COLLECTION_FACTORY_METHODS, COLLECTIONS_FRAMEWORK, LAMBDAS, DIAMOND_OPERATOR, PATTERN_MATCHING_INSTANCEOF, RECORD_PATTERNS
Combo_RecordsPatternSwitch.java: RECORDS, SWITCH_EXPRESSIONS, SWITCH_NULL_DEFAULT, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING
Tiny_VarLambda_Java11.java: VAR_IN_LAMBDA, GENERICS, LAMBDAS
Tiny_BinaryLiterals_Java7.java: UNDERSCORES_IN_LITERALS, BINARY_LITERALS
Java8_NioAPI.java: GENERICS, IO_API, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK, NIO2, METHOD_REFERENCES
Tiny_Scoped_Java25.java: GENERICS, SCOPED_VALUES, LAMBDAS
Tiny_RepeatingAnnotations_Java8.java: REFLECTION, ANNOTATIONS, REPEATING_ANNOTATIONS
Edge_StreamChainAllOperations.java: GENERICS, COLLECTIONS_FRAMEWORK, METHOD_REFERENCES, LAMBDAS, STREAM_API
Edge_RecordImplementsSealed_Java17.java: RECORDS, INNER_CLASSES, SEALED_CLASSES
Combo_VirtualThreadsScoped_Java25.java: GENERICS, SCOPED_VALUES, LAMBDAS
Edge_AnonymousDiamond.java: INNER_CLASSES, GENERICS, COLLECTIONS_FRAMEWORK, DIAMOND_WITH_ANONYMOUS, DIAMOND_OPERATOR
Java8_RepeatingAnnotations.java: REFLECTION, ANNOTATIONS, REPEATING_ANNOTATIONS
Edge_DeeplyNestedGenerics_Java5.java: GENERICS, COLLECTIONS_FRAMEWORK
Tiny_SeqColl_Java21.java: GENERICS, SEQUENCED_COLLECTIONS, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Tiny_TypeAnnotations_Java8.java: GENERICS, ANNOTATIONS, TYPE_ANNOTATIONS
Edge_CollectionFactoryAllTypes.java: GENERICS, COLLECTION_FACTORY_METHODS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Tiny_SequencedCollection_Java21.java: GENERICS, SEQUENCED_COLLECTIONS, COLLECTIONS_FRAMEWORK, DIAMOND_OPERATOR
Edge_MethodReferenceAllTypes.java: GENERICS, METHOD_REFERENCES
Tiny_CollectionFactory_Java9.java: GENERICS, COLLECTION_FACTORY_METHODS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Tiny_ReactiveStreams_Java9.java: GENERICS, CONCURRENT_API, REACTIVE_STREAMS
Combo_DiamondTryVarStream.java: GENERICS, IO_API, VAR, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK, METHOD_REFERENCES, LAMBDAS, STREAM_API, DIAMOND_OPERATOR
Java5_Autoboxing.java: GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Java6_SwingWorker.java: FOR_EACH, INNER_CLASSES, GENERICS, SWING, ANNOTATIONS, MULTI_CATCH, COLLECTIONS_FRAMEWORK, CONCURRENT_API, SWING_WORKER, LAMBDAS
Java8_ConcurrentAPI.java: GENERICS, AUTOBOXING, CONCURRENT_API, LAMBDAS, DIAMOND_OPERATOR
Java16_LocalInterfaces.java: RECORDS, INNER_CLASSES, LAMBDAS, LOCAL_INTERFACES
Java9_DiamondWithAnonymous.java: INNER_CLASSES, GENERICS, ANNOTATIONS, CONCURRENT_API, DIAMOND_WITH_ANONYMOUS, DIAMOND_OPERATOR
Java8_StreamAPI.java: GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING, METHOD_REFERENCES, LAMBDAS, STREAM_API
Java17_SealedClasses.java: RECORDS, INNER_CLASSES, SEALED_CLASSES, PATTERN_MATCHING_INSTANCEOF
Java8_Lambdas.java: GENERICS, COLLECTIONS_FRAMEWORK, LAMBDAS
Java8_DefaultInterfaceMethods.java: INNER_CLASSES, ANNOTATIONS, DEFAULT_INTERFACE_METHODS
Java11_HttpClient.java: HTTP_CLIENT, GENERICS
TestFullyQualifiedNames.java: SWING, REGEX, BASE64_API, AUTOBOXING, CONCURRENT_API, LAMBDAS, VIRTUAL_THREADS, DIAMOND_OPERATOR, OPTIONAL, HTTP_CLIENT, GENERICS, DATE_TIME_API, NIO, COLLECTIONS_FRAMEWORK, NIO2, STREAM_API, AWT, HEX_FORMAT
Java4_Logging.java: REFLECTION, IO_API, LOGGING
Java24_StreamGatherers.java: STREAM_GATHERERS, GENERICS, VAR, COLLECTION_FACTORY_METHODS, COLLECTIONS_FRAMEWORK, AUTOBOXING, METHOD_REFERENCES, LAMBDAS, STREAM_API
Java5_ForEach.java: FOR_EACH, GENERICS, COLLECTIONS_FRAMEWORK
Java1_JavaBeans.java: REFLECTION, JAVABEANS
Java21_RecordPatterns.java: RECORDS, SWITCH_EXPRESSIONS, PATTERN_MATCHING_INSTANCEOF, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING
Java5_Varargs.java: FOR_EACH, VARARGS
Java4_ImageIO.java: IMAGE_IO, IO_API, COLLECTIONS_FRAMEWORK, AWT
Java1_AWT.java: INNER_CLASSES, AWT
Java11_VarInLambda.java: VAR_IN_LAMBDA, GENERICS, LAMBDAS
Java21_VirtualThreads.java: VAR, LAMBDAS, VIRTUAL_THREADS
Java7_DiamondOperator.java: GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING, DIAMOND_OPERATOR
Java5_Generics.java: GENERICS, COLLECTIONS_FRAMEWORK
WildcardImports_Java8.java: OPTIONAL, GENERICS, DATE_TIME_API, COLLECTIONS_FRAMEWORK, STREAM_API, DIAMOND_OPERATOR
LocalEnumEdgeCases_Java16.java: FOR_EACH, INNER_CLASSES, GENERICS, ENUMS, ANNOTATIONS, LOCAL_ENUMS, SWITCH_EXPRESSIONS, LAMBDAS, DIAMOND_OPERATOR, LOCAL_INTERFACES
HttpClientEdgeCases_Java11.java: HTTP_CLIENT, GENERICS, DATE_TIME_API
Java7_MultiCatch.java: IO_API, MULTI_CATCH
StaticImports_Java5.java: STATIC_IMPORT, GENERICS, COLLECTIONS_FRAMEWORK
GenericsEdgeCases_Java5.java: INNER_CLASSES, GENERICS, COLLECTIONS_FRAMEWORK, STREAM_API, DIAMOND_OPERATOR
RecordEdgeCases_Java16.java: RECORDS, GENERICS, DIAMOND_OPERATOR
DiamondOperatorEdgeCases_Java9.java: INNER_CLASSES, GENERICS, ANNOTATIONS, COLLECTIONS_FRAMEWORK, METHOD_REFERENCES, DIAMOND_WITH_ANONYMOUS, DIAMOND_OPERATOR
VirtualThreadsEdgeCases_Java21.java: FOR_EACH, GENERICS, DATE_TIME_API, VAR, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK, CONCURRENT_API, LAMBDAS, VIRTUAL_THREADS, DIAMOND_OPERATOR
ForEachEdgeCases_Java5.java: FOR_EACH, VARARGS, GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING
ExceptionEdgeCases_Java7.java: IO_API, MULTI_CATCH, TRY_WITH_RESOURCES, JDBC
OptionalEdgeCases_Java11.java: OPTIONAL, RECORDS, GENERICS, COLLECTION_FACTORY_METHODS, COLLECTIONS_FRAMEWORK, AUTOBOXING, METHOD_REFERENCES, LAMBDAS, STREAM_API
VarargsEdgeCases_Java5.java: FOR_EACH, VARARGS, INNER_CLASSES, GENERICS, ANNOTATIONS, COLLECTIONS_FRAMEWORK
AnnotationEdgeCases_Java8.java: REFLECTION, ANNOTATIONS, REPEATING_ANNOTATIONS
LambdaEdgeCases_Java8.java: GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING, METHOD_REFERENCES, LAMBDAS, STREAM_API
VarEdgeCases_Java10.java: FOR_EACH, VAR_IN_LAMBDA, GENERICS, DATE_TIME_API, ANNOTATIONS, IO_API, VAR, COLLECTION_FACTORY_METHODS, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK, LAMBDAS
ConcurrentAPIEdgeCases_Java5.java: INNER_CLASSES, GENERICS, ANNOTATIONS, CONCURRENT_API, METHOD_REFERENCES, FORK_JOIN, LAMBDAS, DIAMOND_OPERATOR
PatternMatchingEdgeCases_Java21.java: RECORDS, SWITCH_EXPRESSIONS, SWITCH_NULL_DEFAULT, PATTERN_MATCHING_INSTANCEOF, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING
FullyQualifiedNames_NoImports.java: OPTIONAL, HTTP_CLIENT, GENERICS, DATE_TIME_API, COLLECTIONS_FRAMEWORK, AUTOBOXING, STREAM_API
InterfaceMethodEdgeCases_Java9.java: STATIC_INTERFACE_METHODS, INNER_CLASSES, DATE_TIME_API, PRIVATE_INTERFACE_METHODS, DEFAULT_INTERFACE_METHODS
SwitchEdgeCases_Java21.java: RECORDS, YIELD, SWITCH_EXPRESSIONS, SWITCH_NULL_DEFAULT, SWITCH_MULTIPLE_LABELS, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING
EnumEdgeCases_Java5.java: FOR_EACH, INNER_CLASSES, REFLECTION, GENERICS, ENUMS, ANNOTATIONS, DIAMOND_OPERATOR
TryWithResourcesEdgeCases_Java9.java: INNER_CLASSES, ANNOTATIONS, IO_API, TRY_WITH_RESOURCES, TRY_WITH_EFFECTIVELY_FINAL
AllJava7Features.java: GENERICS, UNDERSCORES_IN_LITERALS, IO_API, MULTI_CATCH, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK, NIO2, BINARY_LITERALS, STRINGS_IN_SWITCH, DIAMOND_OPERATOR
UnnamedVariablesEdgeCases_Java22.java: INNER_CLASSES, UNNAMED_VARIABLES, ANNOTATIONS, VAR, COLLECTION_FACTORY_METHODS, AUTOBOXING, SWITCH_EXPRESSIONS, LAMBDAS, RECORD_PATTERNS, SWITCH_PATTERN_MATCHING, FOR_EACH, RECORDS, GENERICS, TRY_WITH_RESOURCES, COLLECTIONS_FRAMEWORK, SWITCH_NULL_DEFAULT, PATTERN_MATCHING_INSTANCEOF
SealedClassEdgeCases_Java17.java: RECORDS, INNER_CLASSES, SWITCH_EXPRESSIONS, SEALED_CLASSES, SWITCH_PATTERN_MATCHING
ReflectionEdgeCases_Java1.java: INNER_CLASSES, REFLECTION, GENERICS, ANNOTATIONS, COLLECTIONS_FRAMEWORK, LAMBDAS, PATTERN_MATCHING_INSTANCEOF
MixedImports_Java11.java: OPTIONAL, HTTP_CLIENT, GENERICS, COLLECTIONS_FRAMEWORK, METHOD_REFERENCES, STREAM_API, DIAMOND_OPERATOR
AutoboxingEdgeCases_Java5.java: GENERICS, COLLECTIONS_FRAMEWORK, AUTOBOXING
Java21_SwitchPatternMatching.java: RECORDS, INNER_CLASSES, SWITCH_EXPRESSIONS, SWITCH_NULL_DEFAULT, SEALED_CLASSES, SWITCH_PATTERN_MATCHING
"""

# Base directories to search for test files
SEARCH_DIRS = [
    "src/test/resources/feature_tests",
    "src/test/resources/feature_tests/edge_cases",
    "src/test/resources/feature_tests/edge_cases/tiny"
]

def parse_features(line):
    """Parse a file: features line."""
    if ':' not in line:
        return None, None
    parts = line.split(':', 1)
    filename = parts[0].strip()
    features = [f.strip() for f in parts[1].split(',')]
    return filename, features

def find_file(filename):
    """Find the file in the search directories."""
    for dir_path in SEARCH_DIRS:
        full_path = os.path.join(dir_path, filename)
        if os.path.exists(full_path):
            return full_path
    return None

def update_file(filepath, features):
    """Update the file to set Required Features to the given list."""
    with open(filepath, 'r') as f:
        content = f.read()

    # Sort features for consistency
    features_str = ', '.join(sorted(features))

    # Check if there's already a Required Features line
    if '// Required Features:' in content:
        # Replace existing Required Features line
        content = re.sub(
            r'// Required Features:.*',
            f'// Required Features: {features_str}',
            content
        )
    else:
        # Add Required Features after Expected Version or at the start
        lines = content.split('\n')
        new_lines = []
        inserted = False
        for i, line in enumerate(lines):
            new_lines.append(line)
            if not inserted and ('// Expected Version:' in line or '// Version:' in line):
                new_lines.append(f'// Required Features: {features_str}')
                inserted = True

        if not inserted:
            # Add at the very beginning
            new_lines = [f'// Required Features: {features_str}'] + new_lines

        content = '\n'.join(new_lines)

    with open(filepath, 'w') as f:
        f.write(content)

    return True

def main():
    updated = 0
    not_found = []

    for line in errors.strip().split('\n'):
        line = line.strip()
        if not line:
            continue

        filename, features = parse_features(line)
        if not filename or not features:
            continue

        filepath = find_file(filename)
        if not filepath:
            not_found.append(filename)
            continue

        if update_file(filepath, features):
            print(f"Updated: {filepath}")
            updated += 1

    print(f"\nUpdated {updated} files")
    if not_found:
        print(f"Not found: {not_found}")

if __name__ == '__main__':
    main()